##########################################################################
# HOMELAB
##########################################################################

include:
  #########################################################################
  # CORE
  #########################################################################


  #########################################################################
  # UTILITIES
  #########################################################################
  - apps/openspeedtest.yaml

##########################################################################
# NETWORK CONFIGURATION
##########################################################################
networks:
  traefik:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  docker:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.92.0/24