
services:
  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest
    profiles: ["utilities", "all"]
    restart: unless-stopped
    networks:
      traefik:
    # ports:
    #   - '80:3000'
    #   - '443:3001'
    environment:
      # - ENABLE_LETSENCRYPT=True
      # - DOMAIN_NAME=${DOMAIN_NAME}
      - USER_EMAIL=you@yourdomain.com
    labels:
      - homepage.group=Networking
      - homepage.name=Open Speed Test
      - homepage.icon=openspeedtest.png
      - homepage.href=https://fast.${DOMAIN_NAME}/
      - homepage.description=Speed Test
      - homepage.server=localhost
      - homepage.container=openspeedtest
      - traefik.enable=true
      - traefik.http.routers.openspeedtest.rule=Host(`fast.home.lan`)
      - traefik.http.routers.openspeedtest.entrypoints=web
      # - traefik.http.routers.openspeedtest.tls={}
      - traefik.http.routers.openspeedtest.service=openspeedtest-srv
      - traefik.http.services.openspeedtest-srv.loadbalancer.server.port=3000
